"""
Django settings for iRedAdmin project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5%a8$3v!$r*$2!0dfd_wj+^(y+ujbtuzunm5y!#7-b5quzfes+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1',
                'localhost',
                '192.168.100.14',
                ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'mylib',
    'login',
    'myauth',
    'mymenu',
    'index',
    'mail',
]

AUTH_USER_MODEL = 'myauth.User'
#请求登录地址，默认/accounts/login/ 
LOGIN_URL = '/login/'

# AUTHENTICATION_BACKENDS = [  
#     # 自己的权限判断方法  
#     'myauth.backends.ModelBackend',  
#     #系统的权限判断方法  
#     # 'django.contrib.auth.backends.ModelBackend',  
#     ] 

#配置 APPEND_SLASH 为true后，会给所有的网址结尾都会给加上'/'
#APPEND_SLASH=True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#跨域增加忽略
#CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = False #允許所有跨站請求, 且whitelist不會被使用
CORS_ORIGIN_WHITELIST = (
    'localhost',
    '127.0.0.1',
    '192.168.100.14',
)

ROOT_URLCONF = 'iRedAdmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iRedAdmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'iredadmin',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        # 新版本要加入这个参数，主要为了兼容mysql 5.7
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    },
    'mail': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'vmail',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '192.168.100.23',
        'PORT': '3306',
        # 新版本要加入这个参数，主要为了兼容mysql 5.7
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

DATABASE_ROUTERS = ['iRedAdmin.database_router.DatabaseRouter']

#数据库对应app列表
DATABASE_APPS_MAPPING = {
    # example:
    # 'app_name':'database_name',
    'm23': 'mail',
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    {   #包含1000多个拒绝的通用密码
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {   #数字密码无效
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

#使用后时间上差8个小时
#USE_TZ = True

USE_ETAGS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            # 对日志信息进行格式化，每个字段对应了日志格式中的一个字段，更多字段参考官网文档，我认为这些字段比较合适，输出类似于下面的内容
            ## INFO 2016-09-03 16:25:20,067 /home/ubuntu/mysite/views.py views.py views get 29: some info...
            'format': '%(levelname)s %(asctime)s %(pathname)s %(filename)s %(module)s %(funcName)s %(lineno)d: %(message)s'
        }, 
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'main': {
            'datefmt': '%Y-%m-%d %H:%M:%S',
            'format': '%(asctime)s [%(module)s %(levelname)s] %(message)s',
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'standard',
            'filename': os.path.join(BASE_DIR, 'logs', 'access.log')
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        #打印sql语句
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'view': {
            'handlers': ['file'],
            'level': 'DEBUG',
        }
    }
}

#文件上传
MEDIA_URL = '/uploads/'
MEDIA_ROOT =  os.path.join(BASE_DIR, 'uploads')
FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler"
                        )
                        
#自定义错误页
handler403 = 'mylib.views.permission_denied'
handler404 = 'mylib.views.page_not_found'
handler500 = 'mylib.views.page_error'

#默认初始化数据目录
FIXTURE_DIRS = (
    os.path.join(BASE_DIR, 'fixtures'),
)


#iredmail加密算法
DEFAULT_PASSWORD_SCHEME = 'SSHA512'

###################################
# Maildir related.
#

# It's RECOMMEND for better performance. Samples:
# - hashed: domain.ltd/u/s/e/username-2009.09.04.12.05.33/
# - non-hashed: domain.ltd/username-2009.09.04.12.05.33/
MAILDIR_HASHED = True

# Prepend domain name in path. Samples:
# - with domain name: domain.ltd/username/
# - without: username/
MAILDIR_PREPEND_DOMAIN = True

# Append timestamp in path. Samples:
# - with timestamp: domain.ltd/username-2010.12.20.13.13.33/
# - without timestamp: domain.ltd/username/
MAILDIR_APPEND_TIMESTAMP = True