# Generated by Django 2.0 on 2017-12-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=30, verbose_name='真实姓名')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='邮箱')),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('mobile', models.CharField(max_length=15, null=True, verbose_name='移动电话')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
