# Generated by Django 2.0 on 2018-01-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20180115_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_permissions',
            new_name='permissions',
        ),
    ]
